# Generated by Django 5.1.5 on 2025-02-10 22:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('encadrant', 'Encadrant'), ('stagiaire', 'Stagiaire')], default='stagiaire', max_length=20, verbose_name='Rôle')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, default='static/images/admin.png', null=True, upload_to='photos_users/', verbose_name='Photo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Encadrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biographie', models.TextField(verbose_name='Biographie')),
                ('specialite', models.CharField(max_length=100, verbose_name='Spécialité')),
                ('direction', models.CharField(max_length=100, verbose_name='Direction')),
                ('nb_stagiaire_encadres', models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de stagiaires encadrés')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encadrant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=8, unique=True, verbose_name='CIN')),
                ('lieu_de_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('date_de_naissance', models.DateField(verbose_name='Date de naissance')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('niveau_etude', models.CharField(max_length=30, verbose_name="Niveau d'étude")),
                ('specialite', models.CharField(max_length=30, verbose_name='Spécialité')),
                ('universite', models.CharField(max_length=30, verbose_name='Université')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stagiaire', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Sujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='admin_interface.encadrant')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_stage', models.CharField(max_length=100)),
                ('date_debut_stage', models.DateField()),
                ('date_fin_stage', models.DateField()),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents_stages/')),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('note_evaluation', models.FloatField(blank=True, null=True)),
                ('rapport', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('etat_stage', models.CharField(default='non concluant', max_length=20)),
                ('attestation', models.FileField(blank=True, null=True, upload_to='attestations/')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='admin_interface.stagiaire', verbose_name='Stagiaire')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='admin_interface.sujet')),
            ],
        ),
    ]
