# Generated by Django 5.1.5 on 2025-02-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='admin_interface/images/admin.png', null=True, upload_to='photos_users/', verbose_name='Photo'),
        ),
    ]
