# Generated by Django 5.1.7 on 2025-04-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemandeStage',
            new_name='Stage',
        ),
    ]
